#!/usr/bin/bash
magick -gravity center -background transparent -fill "#f5c2e7" -size 128x64 -font Ubuntu caption:mekb -extent 352x96 \( turtle.png -flop -resize 84x84 -background transparent -gravity center \) -geometry -128-0 -composite \( turtle.png -resize 84x84 -background transparent -gravity center \) -geometry +128-0 -composite header.png
magick -gravity center -background transparent -fill "#f5c2e7" -size 72x36 -font Ubuntu caption:"Skills:" skills_text.png
