#!/usr/bin/bash
ROUNDED=(
	"(" +clone
		-alpha transparent
		-fill white -draw "roundRectangle 0,0,%[fx:w],%[fx:h] 16,16"
	")"
	-compose CopyOpacity -composite
)
curl -- "https://img.shields.io/static/v1?label=Discord&message=mekb.&logo=discord&style=for-the-badge&logoColor=f5c2e7&labelColor=1e1e2e&color=f5c2e7" \
	| inkscape -h 32 -p --export-filename - --export-type png \
	| magick png:- \
	"${ROUNDED[@]}" png:- \
	| magick png:- \
	-gravity center -background transparent \
	discord.png
